/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'liyae' at '16-12-7 下午10:21' with Gradle 3.2.1
 *
 * @author liyae, @date 16-12-7 下午10:21
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
